backend:
  name: github
  repo: ybbarng/livvy.byb.kr
  branch: pages # Branch to update (optional; defaults to master)
  base_url: https://blogauth.byb.kr

display_url: https://livvy.byb.kr
media_folder: "/src/pages/images"

publish_mode: simple
public_folder: "img"

accounts:
  - email: ybbarng@gmail.com
    auto_fields:
        authorId: ybbarng
  - email: bluenoche2@gmail.com
    auto_fields:
        authorId: livvy

collections: # A list of collections the CMS should be able to edit
  - name: "posts" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Article" # Used in the UI, ie.: "New Article"
    description: >
      Articles
    folder: "src/pages/articles"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Author ID", name: "authorId", widget: "string"}
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Draft", name: "draft", widget: "boolean", default: False}
      - {label: "Path", name: "path", widget: "string"}
      - {label: "Category", name: "category", widget: "select", options: ['smalltalk', 'study', 'date']}
      - {label: "Tags", name: "tags", widget: "list", default: ""}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "pages"
    label: "Page"
    folder: "src/pages/pages"
    create: false
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}/index"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Layout", name: "layout", widget: "hidden", default: "page"}
      - {label: "Path", name: "path", widget: "string"}
      - {label: "Author ID", name: "authorId", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
